### PR TITLE
Add a command-line version of vfsgen

### LINKED ISSUE #2: Create a binary for simple use.
`vfsgen` is currently a library. To use it, you always need some Go code that provides an input filesystem (like [this](https://github.com/shurcooL/Go-Package-Store/blob/a111049a2ecc18b64d9e7c9a1912d45f0d4dc656/assets_gen.go)). This allows flexibility, but for simple uses it's an extraneous step.

Consider adding a `vfsgen` binary that can be used via command-line interface, similar to `go-bindata` binary.

/cc @nicot Thanks for the suggestion!

### PR DESCRIPTION
**Pull request by slimsag**
- Inclusive of the change at https://github.com/shurcooL/vfsgen/pull/13 (should merge #13 before this one).
- Also depends on the change at https://github.com/shurcooL/httpfs/pull/1
- Fixes #2.

See docs in `main.go` for usage examples / general idea of how it works.

### CODE REVIEW

**Comment by slimsag** [comment]
Currently [inside Appdash](https://github.com/sourcegraph/appdash/tree/master/traceapp/tmpl) we have:

### data.go

```
// +build dev

package tmpl

import "net/http"

// Data is a virtual filesystem that contains template data used by Appdash.
var Data = http.Dir(rootDir)
```

### data_generate.go

```
// +build generate

package main

import (
	"log"

	"github.com/shurcooL/vfsgen"
	"sourcegraph.com/sourcegraph/appdash/traceapp/tmpl"
)

func main() {
	err := vfsgen.Generate(tmpl.Data, vfsgen.Options{
		PackageName:  "tmpl",
		BuildTags:    "!dev",
		VariableName: "Data",
	})
	if err != nil {
		log.Fatalln(err)
	}
}
```

### data_rootdir.go

```
// +build dev

package tmpl

import (
	"go/build"
	"log"
	"path/filepath"
)

// rootDir is the directory containing the html/template template files.
var rootDir = filepath.Join(defaultBase("sourcegraph.com/sourcegraph/appdash/traceapp/tmpl"), "data")

func defaultBase(path string) string {
	p, err := build.Import(path, "", build.FindOnly)
	if err != nil {
		log.Fatal(err)
	}
	return p.Dir
}
```

### data_vfsgen.go (contents obvious)

If this proposal was accepted, we could reduce this down to just:

### data.go

```
// +build dev

package tmpl

import "net/http"

// Data is a virtual filesystem that contains template data used by Appdash.
var Data = vfsgen.DevDir("sourcegraph.com/sourcegraph/appdash/traceapp/tmpl/data")
```

This effectively moves the code out of `data_rootdir.go` into a `vfsgen.DevDir` function itself, since I think it will be used quite often.

### data_generate.go

Then our entire `data_generate.go` file can be removed and `doc.go` can just contain:

```
//go:generate vfsgen -pkg=tmpl -tags=!dev -var=Data
```

I personally find this much easier to track and reason about for the simple case. For more advanced cases, I would certainly want to use the Go library style -- but for simple ones I find this easier.

**Comment by shurcooL** [comment]
Thanks for this very nice proposal & implementation that resolves #2.

The reason I haven't resolved #2 this whole time is because I had some concerns about doing so.

As is mentioned in [CONTRIBUTING.md](https://github.com/shurcooL/vfsgen/blob/master/CONTRIBUTING.md), it would be very helpful to focus on the proposal and reasons/goals for this change, and elaborate on that. I'm happy to think about how to best improve vfsgen and improve its uses, so knowing the motivation is very important. You've written:

> I personally find this much easier to track and reason about for the simple case. For more advanced cases, I would certainly want to use the Go library style -- but for simple ones I find this easier.

I think I understand what you're looking to achieve, but elaborating here would be very helpful.

---

One really important property of the current setup of vfsgen is the [single choice principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) for the filesystem for both development and production modes. For example, a user's input filesystem may start out as:

```Go
var assets = http.Dir("assets")
```

Then become:

```Go
var assets = filter.New(http.Dir("assets"), filter.Extensions(".abc", ".xyz"))
```

```Go
var assets = gopherjs_http.NewFS(filter.New(http.Dir("assets"), filter.Extensions(".abc", ".xyz")))
```

```Go
var assets = union.New(map[string]http.FileSystem{
	"/scripts": gopherjs_http.NewFS(filter.New(http.Dir(filepath.Join("assets", "scripts")), filter.Extensions(".abc", ".xyz"))),
	"/css": cssminify.NewFS(http.Dir(filepath.Join("assets", "css"))),
})
```

But it should be defined in one place, to avoid situations where the development mode works with one set of files:

```Go
var assets = filter.New(http.Dir("new_assets"), filter.Extensions(".new_filter"))
```

But the production version is not updated accordingly and produces slightly different results:

```Go
//go:generate vfsgen -dir=OLD_assets -filter=Extensions(".OLD_filter")
```

**Comment by shurcooL** [comment]
> Then our entire `data_generate.go` file can be removed and `doc.go` can just contain:
>
> ```Go
> //go:generate vfsgen -pkg=tmpl -tags=!dev -var=Data
> ```

What if we could find a way to eliminate the need for a custom `data_generate.go`, but rather have the binary generate it and execute it on the fly. That way, there's still only one place where the filesystem is being defined, and it can continue to use Go code to do fancy stuff in-memory.

So, the go generate directive could look like this:

```Go
//go:generate vfsgen -input="sourcegraph.com/sourcegraph/appdash/traceapp/tmpl".Data -tags=!dev
```

**Comment by shurcooL** [comment]
@slimsag, what do you think of my proposed alternative CLI in the comment above?

I have a working WIP implementation of it, and I didn't run into anything blocking so far.

**Comment by shurcooL** [comment]
To make my proposed alternative easier to review, I've made a PR to the appdash package at https://github.com/sourcegraph/appdash/pull/91. Feel free to review there.

**Comment by slimsag** [comment]
@shurcooL Thanks for the alternative proposal here! I'm not sure that I understand what `-input-tags=dev` effect has? Could you explain it?

**Comment by shurcooL** [comment]
Sure thing!

It's the build tags used when accessing the input filesystem. When compiling Go packages, there's always a context. This controls the build tags of that context.

## Detailed Explanation

For example, consider the following Go package consisting of 3 .go files:

#### main.go

```Go
package main

func main() {
    println(Foo)
}
```

#### alpha.go

```Go
// +build alpha

package main

var Foo = "alpha"
```

#### gamma.go

```Go
// +build !alpha

package main

var Foo = "gamma"
```

Depending on the build tags when building the package, the value of `Foo` variable will vary.

So -input-tags controls the build tags for the source package that is being accessed.

I'm considering renaming -input flag to -source and -input-tags to -source-tags.

**Comment by slimsag** [comment]
Thanks @shurcooL that makes more sense, I understand the need for it now.

The naming around the two flag parameters makes it hard to understand what is going on -- which is unfortunate. Overall I really like the proposal, though I am curious if there is a way we could alleviate the need for the two build tag parameters (maybe there is a way we could just have the output build tag instead, I'll think on this more).

A big :+1: to the general approach here.

**Comment by shurcooL** [comment]
@slimsag I've renamed the flags in https://github.com/shurcooL/appdash/commit/d7acdb675910c3a2da73bc901c4b99872b72f375. Is that an improvement?

IMO it reminds me of `go build -tags=foo package` format more now, and should hopefully be less confusing.

Also note that -tags and -output-tags will not always need to be specified. It's only for advanced usage where you do care about build tags. Otherwise, it can be just `vfsgen -source='"import/path".VariableName'`.

The -source format is inpsired by `gorename` syntax for its -from flag, e.g.:

```bash
gorename -from='"github.com/shurcooL/eX0/eX0-go/packet".ServerUpdatePacket' -to ServerUpdate
```

See its full description [here](http://gotools.org/golang.org/x/tools/refactor/rename#Usage).

**Pull request closed without merging**
